# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 980)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMaximumSize(QtCore.QSize(200, 30))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(700, 450))
        self.groupBox_2.setMaximumSize(QtCore.QSize(1600, 600))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 611, 231))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.groupBox_2, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(700, 450))
        self.groupBox.setMaximumSize(QtCore.QSize(1600, 600))
        self.groupBox.setObjectName("groupBox")
        self.img1 = QtWidgets.QLabel(self.groupBox)
        self.img1.setGeometry(QtCore.QRect(10, 20, 611, 231))
        self.img1.setObjectName("img1")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 5, 1)
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label.setObjectName("label")
        self.result = QtWidgets.QLabel(self.groupBox_3)
        self.result.setGeometry(QtCore.QRect(11, 54, 181, 211))
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.groupBox_3, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "检测"))
        self.left.setText(_translate("MainWindow", "左移"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.img1.setText(_translate("MainWindow", "TextLabel"))
        self.right.setText(_translate("MainWindow", "右移"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "经检查发现："))
        self.result.setText(_translate("MainWindow", "TextLabel"))
